<?php

namespace Nidiap\BlogBundle\Repository;

/**
 * GruposDeTrabalhoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GruposDeTrabalhoRepository extends \Doctrine\ORM\EntityRepository
{
}
