<?php

namespace Nidiap\BlogBundle\Repository;

/**
 * ImagemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagemRepository extends \Doctrine\ORM\EntityRepository
{
}
