<?php

namespace Nidiap\BlogBundle\Repository;

/**
 * LinhasDePesquisaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinhasDePesquisaRepository extends \Doctrine\ORM\EntityRepository
{
}
