<?php

namespace Nidiap\BlogBundle\Repository;

/**
 * ProjetosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetosRepository extends \Doctrine\ORM\EntityRepository
{
}
