<?php

namespace Nidiap\BlogBundle\Repository;

/**
 * SobreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SobreRepository extends \Doctrine\ORM\EntityRepository
{
}
